package com.github.dakusui.jcunit.generators;

import com.github.dakusui.jcunit.constraint.ConstraintManager;
import com.github.dakusui.jcunit.core.factor.Factor;
import com.github.dakusui.jcunit.core.factor.Factors;
import com.github.dakusui.jcunit.core.tuples.Tuple;

import java.util.Iterator;
import java.util.NoSuchElementException;

public abstract class TupleGeneratorBase
    implements TupleGenerator {
  protected Object[] params;
  private Factors factors = null;
  private long    size    = -1;
  private long    cur     = -1;
  private ConstraintManager constraintManager;
  private Class<?>          targetClass;

  @Override
  public void remove() {
    throw new UnsupportedOperationException();
  }

  @Override
  public boolean hasNext() {
    if (size < 0 || this.cur < 0) {
      throw new IllegalStateException();
    }
    return cur < size;
  }

  @Override
  public Iterator<Tuple> iterator() {
    return this;
  }

  @Override
  public Tuple next() {
    if (cur >= size) {
      throw new NoSuchElementException();
    }
    Tuple ret = get(cur);
    cur++;
    return ret;
  }

  @Override
  final public void setFactors(Factors factors) {
    this.factors = factors;
  }

  @Override
  final public Factors getFactors() {
    return this.factors;
  }

  @Override
  final public void setConstraintManager(ConstraintManager constraintManager) {
    this.constraintManager = constraintManager;
  }

  @Override
  final public ConstraintManager getConstraintManager() {
    return this.constraintManager;
  }

  @Override
  final public void init(Object[] processedParameters) {
    this.params = processedParameters;
    this.cur = 0;
    this.size = initializeSchemafulTuples(processedParameters);
  }

  @Override
  public Tuple get(long cur) {
    Tuple.Builder b = new Tuple.Builder();
    for (String f : this.factors.getFactorNames()) {
      b.put(f, factors.get(f).levels.get(getIndex(f, cur)));
    }
    return b.build();
  }

  private int getIndex(String factorName, long testId) {
    Tuple testCase = getSchemafulTuple((int) testId);
    Object l = testCase.get(factorName);
    return getFactor(factorName).levels.indexOf(l);
  }

  @Override
  public long nextId(long tupleId) {
    return (++tupleId < this.size()) ? tupleId : -1;
  }

  @Override
  public long firstId() {
    return 0;
  }

  @Override public void setTargetClass(Class<?> klazz) {
    this.targetClass = klazz;
  }

  @Override public Class<?> getTargetClass() {
    return this.targetClass;
  }

  @Override
  public long size() {
    if (this.size < 0) {
      throw new IllegalStateException();
    }
    return this.size;
  }

  public Factor getFactor(String factorName) {
    return this.factors.get(factorName);
  }

  public abstract Tuple getSchemafulTuple(int tupleId);

  /**
   * Implementation of this method must return a number of test cases generated by this object in total.
   * <p/>
   * o   * @return A number of test cases
   */
  abstract protected long initializeSchemafulTuples(
      Object[] params);
}


