package com.github.dakusui.jcunit.core.factor;

import com.github.dakusui.jcunit.core.FactorField;
import com.github.dakusui.jcunit.core.JCUnitConfigurablePlugin;

import java.lang.reflect.Field;
import java.util.List;

/**
 * Implementations of this class must have a public constructor without any parameters.
 *
 * @param <T> A type to which the levels provided by this class belongs.
 */
public interface LevelsProvider<T> extends JCUnitConfigurablePlugin {
    /**
     * Returns a number of levels generated by this object.
     */
    public int size();

    /**
     * Returns {@code n}-th level of this factor.
     */
    public T get(int n);

    /**
     * Sets the field for which this object generates levels.
     */
    public void setTargetField(Field targetField);

    /**
     * Sets an annotation by which this class is initialized.
     */
    public void setAnnotation(FactorField ann);


    public List<String> getErrorsOnInitialization();
}
