package com.github.dakusui.jcunit.core.factor;

import com.github.dakusui.jcunit.core.FactorField;
import com.github.dakusui.jcunit.core.JCUnitConfigurablePlugin;

import java.lang.reflect.Field;
import java.util.List;

/**
 * Implementations of this class must have a public constructor without any parameters.
 */
public interface LevelsProvider extends JCUnitConfigurablePlugin {
    /**
     * Returns a number of levels generated by this object.
     */
    int size();

    /**
     * Returns {@code n}-th level of this factor.
     */
    Object get(int n);

    /**
     * Sets the field for which this object generates levels.
     */
    void setTargetField(Field targetField);

    /**
     * Sets an annotation by which this class is initialized.
     */
    void setAnnotation(FactorField ann);


    List<String> getErrorsOnInitialization();
}
