package com.github.dakusui.jcunit.core.factor;

import com.github.dakusui.jcunit.core.JCUnitConfigurablePlugin;

import java.util.List;

/**
 * Implementations of this class must have a public constructor without any parameters.
 */
public interface LevelsProvider extends JCUnitConfigurablePlugin {
  /**
   * Returns a number of levels generated by this object.
   */
  int size();

  /**
   * Returns {@code n}-th level of this factor.
   */
  Object get(int n);


  /**
   * Returns a list of error messages detected during initialization.
   */
  List<String> getErrorsOnInitialization();
}
