package com.github.dakusui.jcunit.fsm;

import com.github.dakusui.jcunit.fsm.spec.FSMSpec;
import com.github.dakusui.jcunit.plugins.levelsproviders.MappingLevelsProviderBase;

public class FSMLevelsProvider<SUT, S> extends MappingLevelsProviderBase<Story<SUT, FSMSpec<SUT>>, S> {
  /**
   * The second parameter specifies 'switch coverage', which is equal to a number
   * of actions in 'main' scenario sequence - 1.
   * It represents a number of states passed (switches) during the sequence is executed.
   * If 0 is specified to this parameter, only one action will be performed in a
   * main scenario sequence generated by FSM/JCUnit.
   *
   */
  public FSMLevelsProvider() {
  }
}
