package com.github.dakusui.jcunit.plugins.levelsproviders;

import com.github.dakusui.jcunit.core.BaseBuilder;
import com.github.dakusui.jcunit.plugins.Plugin;

/**
 * Implementations of this class must have a public constructor without any parameters.
 */
public interface LevelsProvider extends Plugin {
  /**
   * Returns a number of levels generated by this object.
   */
  int size();

  /**
   * Returns {@code n}-th level of this factor.
   */
  Object get(int n);


  class Builder implements BaseBuilder<LevelsProvider> {

    @Override
    public LevelsProvider build() {
      return null;
    }
  }
  /**
   * {@inheritDoc}
   */
  abstract class Base implements LevelsProvider {
    public Base() {
    }
  }
}
