package com.github.dakusui.jcunit.plugins.caengines;

/**
 */

import com.github.dakusui.jcunit.core.Checks;
import com.github.dakusui.jcunit.core.factor.Factors;
import com.github.dakusui.jcunit.core.tuples.Tuple;
import com.github.dakusui.jcunit.plugins.Plugin;
import com.github.dakusui.jcunit.plugins.constraints.Constraint;

/**
 * Implementations of this interface must guarantee that a public constructor without
 * any parameters exists.
 */
public interface CoveringArrayEngine extends
    Plugin,
    Iterable<Tuple> {
  void init();

  Factors getFactors();

  void setFactors(Factors factors);

  Constraint getConstraint();

  void setConstraint(Constraint constraint);

  Class<?> getTargetClass();

  void setTargetClass(Class<?> klazz);

  /**
   * Returns a tuple which represents a test case identified by {@code testId}
   */
  Tuple get(long testId);

  /**
   * Returns next valid id.
   */
  long nextId(long testId);

  /**
   * Returns the first valid id.
   */
  long firstId();

  /**
   * Returns total number of test cases generated by the implementations of this interface.
   */
  long size();

  /**
   * A class to build a tuple generator.
   *
   * @param <S> data source type. Can be {@literal @}Param, {@code String}, etc.
   */
  class Builder<S> {

    private final Param.Resolver<S>                    resolver;
    private       Class<? extends CoveringArrayEngine> tupleGeneratorClass;
    private       Factors                              factors;
    private       Constraint                           constraint;
    private       S[]                                  parameters;
    private       Class<?>                             targetClass;

    public static Builder<Object> createSimpleBuilder(Object... arguments) {
      return createSimpleBuilder(IPO2CoveringArrayEngine.class, arguments);
    }

    public static Builder<Object> createSimpleBuilder(Class<? extends CoveringArrayEngine> tupleGeneratorClass, Object... arguments) {
      return new Builder<Object>(
          Param.Resolver.NULL,
          tupleGeneratorClass,
          arguments,
          Constraint.DEFAULT_CONSTRAINT_MANAGER
      );
    }

    public Builder(Param.Resolver<S> resolver, S... arguments) {
      this(resolver, IPO2CoveringArrayEngine.class, arguments, Constraint.DEFAULT_CONSTRAINT_MANAGER);
    }

    public Builder(
        Param.Resolver<S> resolver,
        Class<? extends CoveringArrayEngine> caEngineClass,
        S[] argumentsForCAEngine,
        Constraint cm
    ) {
      this.resolver = Checks.checknotnull(resolver);
      this.tupleGeneratorClass = Checks.checknotnull(caEngineClass);
      this.constraint = Checks.checknotnull(cm);
      this.parameters = argumentsForCAEngine;
    }

    public Builder(CoveringArrayEngine.Builder<S> base) {
      this.resolver = Checks.checknotnull(base.resolver);
      this.tupleGeneratorClass = Checks.checknotnull(base.tupleGeneratorClass);
      this.factors = Checks.checknotnull(base.factors);
      this.constraint = Checks.checknotnull(base.getConstraint());
      this.parameters = Checks.checknotnull(base.parameters);
    }

    public Builder setCAEngineClass(
        Class<? extends CoveringArrayEngine> caEngineClass) {
      this.tupleGeneratorClass = caEngineClass;
      return this;
    }

    public Builder setFactors(Factors factors) {
      this.factors = factors;
      return this;
    }

    public Builder setConstraint(Constraint constraint) {
      this.constraint = constraint;
      return this;
    }

    public Builder setParameters(S[] parameters) {
      this.parameters = parameters;
      return this;
    }

    public Builder setTargetClass(Class<?> targetClass) {
      this.targetClass = targetClass;
      return this;
    }

    public CoveringArrayEngine build() {
      Checks.checknotnull(this.constraint);
      Checks.checknotnull(this.tupleGeneratorClass);
      Checks.checknotnull(this.factors);
      Checks.checknotnull(this.constraint);
      Plugin.Factory<CoveringArrayEngine, S> factory = new Factory<CoveringArrayEngine, S>(
          (Class<CoveringArrayEngine>) this.tupleGeneratorClass,
          this.resolver
      );
      CoveringArrayEngine ret = factory.create(this.parameters);
      ret.setFactors(this.factors);
      ret.setConstraint(this.constraint);
      ret.setTargetClass(this.targetClass);
      ret.init();
      return ret;
    }

    public Constraint getConstraint() {
      return constraint;
    }

    public Factors getFactors() {
      return factors;
    }
  }
}
